export interface IDevice {
  name: string;
  host: string;
  udid: string;
  sdk: string;
  deviceType: 'simulator' | 'emulator' | 'real';
  offline: boolean;
  userBlocked: boolean;
  busy: boolean;
  platform: 'ios' | 'tvos' | 'android';
  realDevice: boolean;
  dashboard_link?: string;
  total_session_count?: number;
  totalUtilizationTimeMilliSec?: any;
  session_id?: any;
  screenWidth?: string;
  screenHeight?: string;
  mjpegServerPort?: number;
  healthStatus?: string;
  healthCheckError?: string;
  lastHealthCheckAt?: number;
  reservedBy?: string;
  reservedUntil?: number;
  reservationReason?: string;
  batteryLevel?: number;
  thermalStatus?: string;
  storageFree?: string;
  tags?: string[];
  sessionProgress?: string;
  totalHealedCount?: number;
  ip?: string;
}
