// Pure helpers behind `npm run sync:tokens`. The launcher's palette is derived
// from the dashboard's web/src/tokens.css rather than hand-copied, so the two
// can't drift apart silently. Kept free of IO so it's unit-testable.

/** Variables the launcher renders as colours (hex → also emitted as rgb channels). */
export const COLOR_VARS = [
  '--bg',
  '--surface',
  '--surface-2',
  '--border',
  '--border-strong',
  '--text',
  '--text-muted',
  '--text-dim',
  '--green',
  '--green-dim',
  '--amber',
  '--red',
  '--blue'
];

/** Variables copied verbatim (already rgba, no alpha companion needed). */
export const PASSTHROUGH_VARS = ['--accent-subtle', '--accent-border'];

/** Read custom properties out of the `:root` block. */
export function parseCssVars(css) {
  const root = css.match(/:root\s*\{([\s\S]*?)\}/);
  if (!root) return {};
  const vars = {};
  for (const m of root[1].matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) {
    vars[m[1]] = m[2].trim();
  }
  return vars;
}

/**
 * '#22c55e' → '34 197 94'. Tailwind needs bare channels to apply opacity
 * modifiers (bg-accent/10) via <alpha-value>. Non-hex values return null.
 */
export function hexToRgbChannels(value) {
  const m = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(value.trim());
  if (!m) return null;
  let hex = m[1];
  if (hex.length === 3) hex = hex.split('').map((c) => c + c).join('');
  const n = parseInt(hex, 16);
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
}

export class MissingTokenError extends Error {
  constructor(name) {
    super(
      `Token ${name} is missing from the dashboard palette (web/src/tokens.css). ` +
        `Either it was renamed/removed there, or mac-app should stop consuming it.`
    );
    this.name = 'MissingTokenError';
  }
}

/** Render the launcher's tokens.css from the dashboard's variables. */
export function generateTokensCss(vars, { colors = COLOR_VARS, passthrough = PASSTHROUGH_VARS } = {}) {
  const lines = [
    '/* GENERATED by `npm run sync:tokens` — do not edit by hand.',
    ' * Source of truth: web/src/tokens.css (the Xenon dashboard palette).',
    ' * Each colour also gets an --*-rgb channel triple so Tailwind can apply',
    ' * opacity modifiers (bg-accent/10) through <alpha-value>.',
    ' */',
    ':root {'
  ];

  for (const name of colors) {
    const value = vars[name];
    if (!value) throw new MissingTokenError(name);
    lines.push(`  ${name}: ${value};`);
    const channels = hexToRgbChannels(value);
    if (channels) lines.push(`  ${name}-rgb: ${channels};`);
  }

  if (passthrough.length) lines.push('');
  for (const name of passthrough) {
    const value = vars[name];
    if (!value) throw new MissingTokenError(name);
    lines.push(`  ${name}: ${value};`);
  }

  lines.push('}', '');
  return lines.join('\n');
}
