// GENERATED by `npm run sync:tokens` — do not edit by hand.
// Source of truth: web/src/tokens.css (the Xenon dashboard's design tokens).
// Each theme's --bg, which the page paints. The main process gives it to the
// window, so the window is the same colour before the page has loaded and at
// its edges while it is resized.

export const WINDOW_BACKGROUND = { dark: '#0e1013', light: '#f6f7f9' } as const;
