/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run "npm run build:schema" to regenerate this file.
 */
import ip from 'ip';

/**
 * Which Android device kinds to include: physical devices, emulators, or both.
 */
export type DeviceTypeToInclude = 'both' | 'real' | 'simulated';
/**
 * Which iOS device kinds to include: physical devices, simulators, or both.
 */
export type DeviceTypeToInclude1 = 'both' | 'real' | 'simulated';

/**
 * Appium configuration schema for the Xenon plugin.
 */
export interface IPluginArgs {
  /**
   * Which mobile platform(s) Xenon should discover and orchestrate.
   */
  platform: 'ios' | 'android' | 'both';
  androidDeviceType: DeviceTypeToInclude;
  /**
   * Allow-list of iOS simulators (by name + sdk) to expose. Empty array means expose all discoverable simulators.
   */
  simulators?: SimulatorConfig[];
  iosDeviceType: DeviceTypeToInclude1;
  /**
   * URL of the Xenon hub this instance should register with as a node (e.g. http://hub.example:4723). Omit to run as a standalone hub.
   */
  hub?: string;
  /**
   * Public host/URL that clients should use to reach this node when running behind a reverse proxy or NAT.
   */
  remoteMachineProxyIP?: string;
  /**
   * List of remote ADB hosts in host:port form (e.g. '192.168.1.50:5037') to discover Android devices on other machines.
   */
  adbRemote?: string[];
  /**
   * Skip the automatic ChromeDriver download performed by uiautomator2. Leave true unless you specifically need Xenon to manage Chrome binaries.
   */
  skipChromeDownload: boolean;
  /**
   * Maximum number of Appium sessions this server runs at once. A new session waits until fewer are running or being started. A live preview, a recording, or an SDK lease that has no session on it does not use a slot; a session started on a leased phone does, but is never held back itself. On a hub the count includes its nodes' phones. A value below 1 means no limit.
   */
  maxSessions: number;
  cloud?: CloudConfig;
  derivedDataPath?: IDerivedDataPath;
  /**
   * Android emulators (AVDs) to boot when the server starts, each as `{ "avdName": "Pixel_7", ... }`. Any other field is a launch option passed to the emulator: `args`, `env`, `language`, `country`, `launchTimeout`, `readyTimeout`, `retryTimes`. Nothing is booted when `platform` is `ios` or `androidDeviceType` is `real`. It does not limit which emulators are discovered: every emulator that is running is found, as `bootedEmulators` allows.
   */
  emulators?: EmulatorConfig[];
  proxy?: AxiosProxy;
  /**
   * How long (ms) a session request waits for a free device before failing.
   */
  deviceAvailabilityTimeoutMs: number;
  /**
   * How often (ms) the session queue polls for a free device while waiting. Runs only while a create is actively waiting for a busy/unsynced device, so a tighter interval cuts the wait without steady-state cost.
   */
  deviceAvailabilityQueryIntervalMs: number;
  /**
   * How often (ms) a node pushes its current device list to the hub. Only used when `hub` is set.
   */
  sendNodeDevicesToHubIntervalMs: number;
  /**
   * How often (ms) the hub prunes devices from nodes that have stopped heartbeating.
   */
  checkStaleDevicesIntervalMs: number;
  /**
   * How often (ms) to re-evaluate manually-blocked devices and the session reconciler that frees orphaned busy devices.
   */
  checkBlockedDevicesIntervalMs: number;
  /**
   * Default Appium newCommandTimeout (seconds) applied when a client does not send one. Also drives the reconciler that releases devices idle past this threshold.
   */
  newCommandTimeoutSec: number;
  /**
   * Host/IP advertised in device URLs and the dashboard. Use auto (default), 0.0.0.0, 127.0.0.1, or localhost to pick the best LAN-reachable IPv4 (e.g. 192.168.x.x). Set an explicit address to override.
   */
  bindHostOrIp: string;
  /**
   * Keep a full record of each Appium session for the dashboard: its commands, screenshots, logs and performance on the Sessions page, and its heals in Selector Health (self-healing learns selectors only from recorded sessions). Without it, a session on this server's own phones isn't listed at all, while a hub still lists the sessions it sends to its nodes' phones, with their result, why they failed and their video. A node's own setting records nothing for its hub's sessions. Video is recorded either way unless the session turns it off. The dashboard itself is always served at /xenon/, whatever this is set to.
   */
  enableDashboard: boolean;
  /**
   * Only discover iOS simulators that are already booted. Recommended on machines with many installed simulators — avoids allocating WDA/MJPEG ports for shutdown sims (the WDA pool is 8100-8199, 100 ports).
   */
  bootedSimulators: boolean;
  /**
   * Only discover Android emulators that are already booted.
   */
  bootedEmulators?: boolean;
  /**
   * At startup, also forget what was set for this server's own phones (team, tags, maintenance, reservations), so each comes back as a new phone. Without it a phone keeps those whenever it reconnects, through restarts. A node forgets them for every phone it has; a hub keeps its nodes' phones and theirs either way.
   */
  removeDevicesFromDatabaseBeforeRunningThePlugin: boolean;
  /**
   * Default interval (ms) between background device health checks. Overridden when `healthCheckSchedule` is set. Default 5 minutes — frequent enough to keep battery/thermal badges fresh without hammering devices. A value saved on the dashboard's Settings page replaces this one.
   */
  healthCheckIntervalMs: number;
  /**
   * Cron expression for the device health-check job (e.g. '0 * * * *' for hourly). When set, takes precedence over `healthCheckIntervalMs`. A schedule saved on the dashboard's Settings page replaces this one.
   */
  healthCheckSchedule?: string;
  /**
   * Database backend. The published plugin stores its data in SQLite only, and each server, hub or node, has its own database. postgresql is accepted so older configs still start, and has no effect: the database URL decides.
   */
  databaseProvider?: 'sqlite' | 'postgresql';
  /**
   * Where the SQLite database lives, as `file:/path/to/xenon.db`. Falls back to the DATABASE_URL env var, then to a file under ~/.cache/xenon. A PostgreSQL URL stops the server at startup.
   */
  databaseUrl?: string;
  /**
   * AI provider for the LLM healing tier and visual analysis. Also controlled by XENON_AI_PROVIDER. A provider chosen on the dashboard's AI engine page replaces this one, and applies from the next AI call without a restart.
   */
  aiProvider?: 'gemini' | 'openai' | 'anthropic' | 'ollama';
  /**
   * Override the default model for the selected `aiProvider` (e.g. 'gemini-1.5-pro', 'gpt-4o', 'claude-sonnet-4-6'). Falls back to XENON_AI_MODEL. A model saved through the dashboard's settings (`POST /xenon/api/config`) replaces this one.
   */
  aiModel?: string;
  /**
   * Custom base URL for the AI provider (e.g. a local Ollama server or an OpenAI-compatible gateway). Falls back to XENON_AI_BASE_URL. A base URL saved through the dashboard's settings (`POST /xenon/api/config`) replaces this one.
   */
  aiBaseUrl?: string;
  /**
   * Gemini API key. Prefer setting XENON_GEMINI_API_KEY (or GEMINI_API_KEY) via environment instead of committing it to a config file.
   */
  geminiApiKey?: string;
  /**
   * OpenAI API key. Prefer setting XENON_OPENAI_API_KEY (or OPENAI_API_KEY) via environment.
   */
  openaiApiKey?: string;
  /**
   * Anthropic API key. Prefer setting XENON_ANTHROPIC_API_KEY (or ANTHROPIC_API_KEY) via environment.
   */
  anthropicApiKey?: string;
  /**
   * Enable the self-healing pipeline (etalon recovery → Native → Fuzzy XML → OCR → Visual AI → LLM) for failed findElement calls. A value saved with the AI self-healing switch on the dashboard's Settings page replaces this one, and applies from the next command without a restart. A session can limit the tiers it uses with `xe:options.healingTiers` (`[]` turns healing off for that session); it cannot turn healing on where this is off.
   */
  enableSelfHealing: boolean;
  /**
   * Builds/sessions older than this many days are purged by the cleanup job. A value saved on the dashboard's Maintenance page replaces this one, and applies at the next cleanup run without a restart.
   */
  buildCleanupDays: number;
  /**
   * Maximum number of builds to retain. Oldest-first eviction beyond this cap regardless of `buildCleanupDays`. A value saved on the dashboard's Maintenance page replaces this one.
   */
  buildCleanupMaxCount: number;
  /**
   * Cron expression for the retention job. Default '0 0 * * *' runs at midnight. A schedule saved on the dashboard's Maintenance page replaces this one, and takes effect at once.
   */
  buildCleanupSchedule: string;
  /**
   * When true, the cleanup job also deletes session video recordings and screenshots from disk (not just DB rows). A value saved on the dashboard's Maintenance page replaces this one.
   */
  deleteBuildAssets: boolean;
  /**
   * Live Devices recordings older than this many days are purged (DB row + files) by the cleanup job. Runs on `buildCleanupSchedule`.
   */
  recordingCleanupDays?: number;
  /**
   * Maximum number of recordings to retain. Oldest-first eviction beyond this cap regardless of `recordingCleanupDays`.
   */
  recordingCleanupMaxCount?: number;
  /**
   * Failed recordings hold no playable file, so they are purged on this much shorter window than `recordingCleanupDays`.
   */
  recordingFailedCleanupDays?: number;
  /**
   * How often (ms) each active session writes a heartbeat. The orphan sweeper uses ~3× this interval to detect abandoned sessions.
   */
  sessionHeartbeatIntervalMs: number;
  /**
   * Emit structured JSON log lines instead of human-readable text. Recommended for shipping logs to a log aggregator. Off by default. When unset, the XENON_JSON_LOGGING environment variable decides (`true` turns it on); setting this to true or false overrides the variable.
   */
  enableJsonLogging?: boolean;
  /**
   * Whether to verify TLS certificates for internal outgoing requests. Default is true. Set to false only for dev/test.
   */
  tlsRejectUnauthorized?: boolean;
  /**
   * Disable API key authentication for all /xenon/api/* endpoints. Use only in local dev environments.
   */
  authDisabled?: boolean;
  interceptor?: InterceptorConfig;
  /**
   * Server-wide hard cap on simultaneous free-form (non-session) screen recordings across all users. Automation session recording is exempt and not counted against this cap. Default 4. When unset, the XENON_MAX_CONCURRENT_RECORDINGS environment variable is used if it is a whole number of at least 1.
   */
  maxConcurrentRecordings?: number;
  /**
   * Directory for free-form recording artifacts. When unset, the XENON_RECORDINGS_ASSETS_PATH environment variable is used if it is set, else ~/.cache/xenon/assets/sessions/recordings.
   */
  recordingsAssetsPath?: string;
  autowait?: AutowaitConfig;
  streaming?: StreamingConfig;
  /**
   * Record CPU and memory every 2 s for each session on this server's own phones (Android: the app under test and the device; iPhone: device CPU), shown in the session page's Performance panel. Needs the dashboard.
   */
  sessionMetrics?: boolean;
}
export interface SimulatorConfig {
  name: string;
  sdk: string;
  [k: string]: unknown;
}
/**
 * Cloud configuration object. Should be provided via config file.
 */
export interface CloudConfig {
  /**
   * Name of the cloud provider (e.g. browserstack, saucelabs, pcloudy, lambdatest)
   */
  cloudName: string;
  /**
   * URL of the cloud provider hub
   */
  url: string;
  /**
   * API Key for the cloud provider
   */
  apiKey: string;
  /**
   * API URL for the cloud provider
   */
  apiUrl?: string;
  devices: CloudDevice[];
}
/**
 * Device configuration object
 */
export interface CloudDevice {
  deviceName?: string;
  platform?: string;
  os_version?: string;
  platformVersion?: string;
  pCloudy_DeviceManufacturer?: string;
  pCloudy_DeviceVersion?: string;
  [k: string]: unknown;
}
/**
 * Map of derived data paths for iOS simulators/devices.
 */
export interface IDerivedDataPath {
  [k: string]: string;
}
export interface EmulatorConfig {
  avdName: string;
  [k: string]: unknown;
}
/**
 * Proxy configuration object. Contains 'host', 'port', 'auth', 'protocol'.
 */
export interface AxiosProxy {
  host?: string;
  port?: number;
  protocol?: 'http' | 'https';
  auth?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Network request interceptor configuration.
 */
export interface InterceptorConfig {
  /**
   * Capture the network traffic of every Android session on this server that doesn't say otherwise. A session turns capture on or off for itself with its interceptor capability (xe:interceptor.enabled, xe:options.interceptor.enabled, the flat interceptorEnabled, ...), which wins over this. While capture runs, the phone's global HTTP proxy points at Xenon; it is put back when the session ends, however it ends.
   */
  enabled?: boolean;
  /**
   * Maximum number of captured requests to retain in-memory per session before evicting oldest. The default for sessions whose interceptor capability doesn't set bufferSize.
   */
  bufferSize?: number;
  /**
   * Whether to capture request/response bodies. Disable for privacy or to reduce memory usage. The default for sessions whose interceptor capability doesn't set captureBodies.
   */
  captureBodies?: boolean;
}
/**
 * Implicit-wait configuration for findElement/findElements and pre-action enabled checks.
 */
export interface AutowaitConfig {
  /**
   * Enable autowait globally. Sessions can override via the `xenon: setAutowaitProperties` execute script.
   */
  enabled?: boolean;
  /**
   * How long (ms) to keep retrying findElement before throwing NoSuchElement. Self-healing still runs once this timeout expires.
   */
  timeoutMs?: number;
  /**
   * Sleep (ms) between findElement retries while waiting for the element to appear.
   */
  intervalBetweenAttemptsMs?: number;
  /**
   * Action commands (click, setValue, clear) for which the pre-action elementEnabled check should be skipped.
   */
  excludeEnabledCheck?: string[];
}
/**
 * Live-streaming options.
 */
export interface StreamingConfig {
  /**
   * Android live preview: false/omitted = MJPEG; true = H.264 via scrcpy; { "source": "scrcpy" | "screenrecord" } to pick the capture source explicitly. Falls back to MJPEG when unsupported.
   */
  androidH264?:
    | boolean
    | {
        source?: 'scrcpy' | 'screenrecord';
      };
}

export const DefaultPluginArgs: IPluginArgs = {
  platform: 'both',
  iosDeviceType: 'both',
  androidDeviceType: 'both',
  skipChromeDownload: true,
  hub: undefined,
  maxSessions: 8,
  derivedDataPath: undefined,
  adbRemote: [],
  remoteMachineProxyIP: undefined,
  proxy: undefined,
  emulators: [],
  simulators: [],
  deviceAvailabilityTimeoutMs: 300000,
  // Poll interval while a session-create waits for a busy/unsynced target device.
  // Only runs during an active wait (the loop exits immediately when the device
  // is available), so a tight interval costs nothing in steady state but avoids
  // quantizing the wait into ~10s chunks — the misdiagnosed "~65s cold create"
  // was mostly ~5 such 10s cycles, not uia2 APK install. Override per-request
  // with appium:deviceRetryInterval.
  deviceAvailabilityQueryIntervalMs: 1000,
  sendNodeDevicesToHubIntervalMs: 30000,
  checkStaleDevicesIntervalMs: 30000,
  checkBlockedDevicesIntervalMs: 30000,
  newCommandTimeoutSec: 60,
  cloud: undefined,
  bindHostOrIp: 'auto',
  enableDashboard: false,
  bootedSimulators: false,
  healthCheckIntervalMs: 300000,
  healthCheckSchedule: undefined,
  removeDevicesFromDatabaseBeforeRunningThePlugin: false,
  databaseProvider: undefined,
  databaseUrl: undefined,
  aiProvider: undefined,
  aiModel: undefined,
  aiBaseUrl: undefined,
  geminiApiKey: undefined,
  openaiApiKey: undefined,
  anthropicApiKey: undefined,
  enableSelfHealing: true,
  buildCleanupDays: 30,
  buildCleanupMaxCount: 100,
  buildCleanupSchedule: '0 0 * * *',
  deleteBuildAssets: true,
  recordingCleanupDays: 30,
  recordingCleanupMaxCount: 100,
  recordingFailedCleanupDays: 2,
  sessionHeartbeatIntervalMs: 30000,
  autowait: {
    enabled: false,
    timeoutMs: 10000,
    intervalBetweenAttemptsMs: 500,
    excludeEnabledCheck: [],
  },
};
