/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run "npm run build:schema" to regenerate this file.
 */
import ip from 'ip';

export type DeviceTypeToInclude = 'both' | 'real' | 'simulated';
export type DeviceTypeToInclude1 = 'both' | 'real' | 'simulated';

/**
 * Appium configuration schema for the Xenon plugin.
 */
export interface IPluginArgs {
  platform: 'ios' | 'android' | 'both';
  androidDeviceType: DeviceTypeToInclude;
  simulators?: {
    [k: string]: unknown;
  }[];
  iosDeviceType: DeviceTypeToInclude1;
  hub?: string;
  remoteMachineProxyIP?: string;
  adbRemote?: string[];
  skipChromeDownload: boolean;
  maxSessions: number;
  cloud?: CloudConfig;
  derivedDataPath?: IDerivedDataPath;
  emulators?: {
    [k: string]: unknown;
  }[];
  proxy?: AxiosProxy;
  deviceAvailabilityTimeoutMs: number;
  deviceAvailabilityQueryIntervalMs: number;
  sendNodeDevicesToHubIntervalMs: number;
  checkStaleDevicesIntervalMs: number;
  checkBlockedDevicesIntervalMs: number;
  newCommandTimeoutSec: number;
  bindHostOrIp: string;
  enableDashboard: boolean;
  bootedSimulators: boolean;
  removeDevicesFromDatabaseBeforeRunningThePlugin: boolean;
  healthCheckIntervalMs: number;
  healthCheckSchedule?: string;
  databaseProvider?: 'sqlite' | 'postgresql';
  databaseUrl?: string;
  aiProvider?: 'gemini' | 'openai' | 'anthropic' | 'ollama';
  aiModel?: string;
  aiBaseUrl?: string;
  geminiApiKey?: string;
  openaiApiKey?: string;
  anthropicApiKey?: string;
  enableSelfHealing: boolean;
  buildCleanupDays: number;
  buildCleanupMaxCount: number;
  buildCleanupSchedule: string;
  deleteBuildAssets: boolean;
  sessionHeartbeatIntervalMs: number;
  enableJsonLogging: boolean;
  /**
   * Whether to verify TLS certificates for internal outgoing requests. Default is true. Set to false only for dev/test.
   */
  tlsRejectUnauthorized?: boolean;
}
/**
 * Cloud configuration object. Should be provided via config file.
 */
export interface CloudConfig {
  /**
   * Name of the cloud provider (e.g. browserstack, saucelabs, pcloudy, lambdatest)
   */
  cloudName: string;
  /**
   * URL of the cloud provider hub
   */
  url: string;
  /**
   * API Key for the cloud provider
   */
  apiKey: string;
  /**
   * API URL for the cloud provider
   */
  apiUrl?: string;
  devices: CloudDevice[];
}
/**
 * Device configuration object
 */
export interface CloudDevice {
  deviceName?: string;
  platform?: string;
  os_version?: string;
  platformVersion?: string;
  pCloudy_DeviceManufacturer?: string;
  pCloudy_DeviceVersion?: string;
  [k: string]: unknown;
}
/**
 * Map of derived data paths for iOS simulators/devices.
 */
export interface IDerivedDataPath {
  [k: string]: string;
}
/**
 * Proxy configuration object. Contains 'host', 'port', 'auth', 'protocol'.
 */
export interface AxiosProxy {
  host?: string;
  port?: number;
  protocol?: 'http' | 'https';
  auth?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}

export const DefaultPluginArgs: IPluginArgs = {
  platform: 'both',
  iosDeviceType: 'both',
  androidDeviceType: 'both',
  skipChromeDownload: true,
  hub: undefined,
  maxSessions: 8,
  derivedDataPath: undefined,
  adbRemote: [],
  remoteMachineProxyIP: undefined,
  proxy: undefined,
  emulators: [],
  simulators: [],
  deviceAvailabilityTimeoutMs: 300000,
  deviceAvailabilityQueryIntervalMs: 10000,
  sendNodeDevicesToHubIntervalMs: 30000,
  checkStaleDevicesIntervalMs: 30000,
  checkBlockedDevicesIntervalMs: 30000,
  newCommandTimeoutSec: 60,
  cloud: undefined,
  bindHostOrIp: ip.address(),
  enableDashboard: false,
  bootedSimulators: false,
  healthCheckIntervalMs: 30000,
  healthCheckSchedule: undefined,
  removeDevicesFromDatabaseBeforeRunningThePlugin: false,
  databaseProvider: undefined,
  databaseUrl: undefined,
  aiProvider: undefined,
  aiModel: undefined,
  aiBaseUrl: undefined,
  geminiApiKey: undefined,
  openaiApiKey: undefined,
  anthropicApiKey: undefined,
  enableSelfHealing: true,
  buildCleanupDays: 30,
  buildCleanupMaxCount: 100,
  buildCleanupSchedule: '0 0 * * *',
  deleteBuildAssets: true,
  sessionHeartbeatIntervalMs: 30000,
  enableJsonLogging: false,
};
